### PR TITLE
Output Console

### PR DESCRIPTION
**Pull request by Stefterv**
I added a simple output pane to see what the sketch outputs to the console
still a lot of stuff to add but it works
screen shot 2015-09-15 at 12 24 16 1

### CODE REVIEW

**Comment by jslvtr** [comment]
Please merge, this would be a fantastic addition (also to get error messages!).

**Comment by bleikamp** [comment]
@jslvtr Merged, thanks for the ping—had forgotten about this.

@Stefterv Sorry for taking so long to merge, thanks for the contribution!

**Comment by jslvtr** [comment]
@bleikamp Awesome! Thanks for that! :+1:

**Comment by Stefterv** [comment]
@bleikamp No problem, thank you for merging!

**Pull request merged**
